steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/neuralworks-391706/neuralworks_img', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/neuralworks-391706/neuralworks_img']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'api-service', '--image', 'gcr.io/neuralworks-391706/neuralworks_img', '--platform', 'managed', '--region', 'us-west1-a', '--allow-unauthenticated']
