steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/neuralworks-391706/neuralworks_img', '.']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/neuralworks-391706/neuralworks_img']

  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'neuralworks-service', '--image', 'gcr.io/neuralworks-391706/neuralworks_img', '--region', 'us-west2', '--platform', 'managed', '--allow-unauthenticated', '--port', '5000']